env: "local"
app_name: "Url-Shortener"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса и отправку ответа (время на обработку не ограничено)
  idle_timeout: 60s # время жизни соединения с клиентом
  # (используем одно соединение на неск запросов от клиента если между ними небольшие промежутки)
  # по сути время которое мы ждем повторного запроса от клиента прежде чем оборвать соединение
